---
# tasks file for ansible_apt
- name: Include distribution specific variables
  include_vars: "{{ ansible_facts.distribution }}.yml"

- name: Configure apt conf.d
  template:
    src: "etc/apt/apt.conf.d/{{ item }}"
    dest: "/etc/apt/apt.conf.d/{{ item | basename | regex_replace('.j2', '') }}"
    owner: root
    group: root
    mode: 0644
  with_fileglob: '../templates/etc/apt/apt.conf.d/*.j2'
  become: true

- name: Configure apt preferences
  template:
    src: "etc/apt/preferences.d/{{ item }}"
    dest: "/etc/apt/preferences.d/{{ item | basename | regex_replace('.j2', '') }}"
    owner: root
    group: root
    mode: 0644
  with_fileglob: '../templates/etc/apt/preferences.d/*.j2'
  become: true

- name: Make sure the default sources.lists file exists
  ansible.builtin.template:
    src: etc/apt/sources.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644
  become: true

- name: Install packages
  ansible.builtin.apt:
    name: "{{ apt_required_packages + apt_base_packages + apt_aditional_packages }}"
    state: "{{ apt_install_state | default('present') }}"
  become: true

- name: Upgrade packages
  ansible.builtin.apt:
    update_cache: '{{ apt_update_cache }}'
    upgrade: '{{ apt_upgrade }}'
    autoclean: '{{ apt_autoclean }}'
    autoremove: '{{ apt_autoremove }}'
    force_apt_get: '{{ apt_force_apt_get }}'
  become: true

- name: Install unattended-upgrades
  apt:
    name: "{{ apt_unattended_upgrades_packages }}"
    state: present
  when: apt_install_unattended_upgrades
  become: true

- name: Configure unattended-upgrades
  template:
    src: "etc/apt/apt.conf.d/{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - 20auto_upgrades
    - 50unattended-upgrades
  become: true
