---
# tasks file for ansible_apt
- name: Include distribution specific variables
  include_vars: "{{ ansible_facts.distribution }}.yml"

- name: Create custom configuration directories
  ansible.builtin.file:
    path: /etc/apt/{{ item.path }}
    state: directory
    owner: root
    group: root
    mode: 0755
  with_community.general.filetree: templates/
  when: item.state == 'directory'
  become: true

- name: Copy custom configuration files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: /etc/apt
    owner: root
    group: root
    mode: 0644
  with_community.general.filetree: templates/
  when: item.state == "file"
  become: true

- name: Make sure the default sources.lists file exists
  ansible.builtin.template:
    src: etc/apt/sources.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644
  become: true

- name: Install packages
  ansible.builtin.apt:
    name: "{{ apt_required_packages + apt_base_packages + apt_aditional_packages }}"
    state: "{{ apt_install_state | default('present') }}"
  become: true

- name: Upgrade packages
  ansible.builtin.apt:
    update_cache: '{{ apt_update_cache }}'
    upgrade: '{{ apt_upgrade }}'
    autoclean: '{{ apt_autoclean }}'
    autoremove: '{{ apt_autoremove }}'
    force_apt_get: '{{ apt_force_apt_get }}'
  become: true

- name: Install unattended-upgrades
  apt:
    name: "{{ apt_unattended_upgrades_packages }}"
    state: present
  when: apt_install_unattended_upgrades
  become: true

- name: Configure unattended-upgrades
  template:
    src: "etc/apt/apt.conf.d/{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - 20auto_upgrades
    - 50unattended-upgrades
  become: true
