---
# tasks file for ansible_apt
- name: Include distribution specific variables
  include_vars: "{{ ansible_facts.distribution }}.yml"

- name: Make sure the default sources.lists file exists
  ansible.builtin.template:
    src: etc/apt/sources.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644
    modification_time: preserve
  become: true

- name: Install packages
  ansible.builtin.apt:
    name: "{{ apt_base_packages + apt_aditional_packages }}"
    state: "{{ apt_install_state | default('present') }}"
  become: true

- name: Upgrade packages
  ansible.builtin.apt:
    update_cache: '{{ apt_update_cache }}'
    upgrade: '{{ apt_upgrade }}'
    autoclean: '{{ apt_autoclean }}'
    autoremove: '{{ apt_autoremove }}'
    force_apt_get: '{{ apt_force_apt_get }}'
  become: true


